name: Deploy MkDocs to GitHub Pages

permissions:
  contents: read
  pages: write

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install mkdocs-glightbox

      - name: Build site
        run: mkdocs build --clean

      - name: Deploy to Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GH_PAGES_TOKEN }}
          publish_dir: ./site/   # ändere hier auf ./public/, falls dein mkdocs.yml public nutzt
